### ISSUE TITLE
[Bug] After creating a new custom channel, settings aren't selectable

### ISSUE THREAD

**Issue by failcoder** [failcoder/Supervillain_UI#109]
_From @penguinsane on February 20, 2015 19:26_

When I make a new custom chat channel, I usually click a tab and try to select which one it shows up in... but I can't, because it looks like this until I reload: http://puu.sh/g3plF/7810a9e3f0.jpg

_Copied from original issue: failcoder/SVUI-Kit#70_

**Comment by penguinsane** [comment]
Still an issue, but also to note, I have to reload constantly if I want to change channel colors or enable class colors, etc. This especially happens after creating a new character, after playing for a couple mins.

**Comment by failcoder** [comment]
This was recently fixed. Let me know if it happens again.

**Comment by penguinsane** [comment]
Appears to be working fine. Can close if you want, will open if I see it happen again!
