### ISSUE TITLE
[Bug] Can't move bag slots around, can't put new bags into bank slots

### ISSUE THREAD

**Issue by failcoder** [failcoder/Supervillain_UI#110]
_From @penguinsane on February 17, 2015 21:48_

Same issue as was happening before off and on, happening again.

Can sometimes move bag slots around, but it's hard to actually put new bags into slots, especially in the bank. Have to disable bag module to do it.

_Copied from original issue: failcoder/SVUI-Kit#68_

**Comment by failcoder** [comment]
Nothing has changed in bags though. Lets try this, tell me EXACTLY what you did when it happened (ie... what specific bag it was, was the bag slot empty prior to the attempt, what was the actual outcome?).

**Comment by failcoder** [comment]
_From @penguinsane on February 17, 2015 22:44_

Purchased first two bank bag slot, attempted to move already-soulbound Netherweave Bag into empty bank slot. Drag bag over, attempting to click... nothing happens. No error, just doesn't happen.

For the most part, it seems like the regular inventory is working just fine. I seem to be able to move bags around, take them off, put them back.

The bank is where this problem is right now.

Made a gif for you of what's happening: http://puu.sh/g1szP/bec43e7e57.gif

**Comment by failcoder** [comment]
BOOYA!! Fixed!!!!

**Comment by failcoder** [comment]
_From @penguinsane on February 18, 2015 6:28_

Hrm. Fresh install, deleted all SVUI-related .WTF files, still can't drag my Netherweave Bag into my available bank slot. :(

**Comment by failcoder** [comment]
You are KILLING me smalls!
Updated, try it now.

**Comment by failcoder** [comment]
_From @penguinsane on February 18, 2015 10:22_

Well I'm sorry! I'm just trying to do what you keep me around for, lol.

Updated, no change. (Don't hurt me.)

**Comment by failcoder** [comment]
_From @Nyrin on February 21, 2015 3:50_

I am now having this problem. i can take stuff out of my bank bags, remove the bags from the slot, but i can not equip the bag in the bank slot.

**Comment by failcoder** [comment]
_From @Nyrin on February 21, 2015 3:55_

had to disable all of svui to add the bags to bank slots.

**Comment by failcoder** [comment]
This issue is going under the knife this week. I have a few ideas to test that will hopefully eliminate this long standing problem.

**Comment by penguinsane** [comment]
We established what the issue may be, but just logging it. :)
Click, hold, dragging bags works fine.

Click and just picking up, then trying to click them into slots does not.
