### ISSUE TITLE
Minimap Treasure Tracking

### ISSUE THREAD

**Issue by failcoder** [failcoder/Supervillain_UI#112]
_From @Elrainia on February 17, 2015 17:32_

The arrows indicating treasure in the minimap don't display after a zone change.  Issuing a /reloadui resolves the issue.

Edit: Sorry this issue is with the live version - don't know if it's fixed in the test version.

_Copied from original issue: failcoder/SVUI-Kit#64_

**Comment by failcoder** [comment]
There has since been an adjustment that should have fixed this. Please re-test and let me know.

**Comment by Elrainia** [comment]
All sorted a long time ago :-)  Many thanks for all your hard work…

Malc
