### ISSUE TITLE
Achievement completion pop-up

### ISSUE THREAD

**Issue by LanceB71** [failcoder/Supervillain_UI#117]
I'm seeing duplicate pop-ups of achievement progress/completion.  I cannot find any setting that I have made that could cause this.  Any ideas?
![wowscrnshot_041215_155056](https://cloud.githubusercontent.com/assets/11777732/7107990/e0a1f156-e12c-11e4-9603-95ea5ce8a1cc.jpg)

**Comment by failcoder** [comment]
Does this happen every time , or only on occasion?

**Comment by LanceB71** [comment]
Was on a regular basis, but have not seen it since update.  I will continue to monitor it and keep you posted.  Thanks!!

**Comment by LanceB71** [comment]
Haven't seen the issue rear its head since the latest updates.  Will continue to monitor - closing for now.
