### ISSUE TITLE
Bags not maintaing sort

### ISSUE THREAD

**Issue by LanceB71** [failcoder/Supervillain_UI#118]
Is there a known issue with Adibags and them not keeping sort?  Seems this happens either after AFK or after a long duration of not opening bags.  Reload UI does return the bags to normal.

![wowscrnshot_041215_160525](https://cloud.githubusercontent.com/assets/11777732/7108019/078a76ac-e12e-11e4-8366-0c8be0d5991d.jpg)

**Comment by failcoder** [comment]
If you are using adibags then see if this happens without the adding SVUI_Inventory enabled

**Comment by LanceB71** [comment]
Doesn't seem to be occurring now with the latest updates.  Will keep an eye on it - closing for now.
