### ISSUE TITLE
[Bug?] New abilities don't show up on action bars automatically

### ISSUE THREAD

**Issue by penguinsane** [failcoder/Supervillain_UI#123]
One of Blizzard's features is that new abilities, especially at low levels, pop up automatically as you gain them. It makes it easier to see if you've gotten anything new.

With SVUI enabled, this does not happen.

**Comment by failcoder** [comment]
I added code to allow abilities to auto-fill the action bars recently. Next time you are leveling an alt, let me know if there are any more issues.

**Comment by penguinsane** [comment]
Looks like it works great. Abilities are auto-filling and there's a glow that goes away on mouseover. Thank you so much!
