### ISSUE TITLE
Profiles resetting

### ISSUE THREAD

**Issue by OrbitStorm** [failcoder/Supervillain_UI#124]
Upon each log-in, or switching characters, SV's options reset. I've tried saving a "global" profile and loading from it or changing to it, to no avail. This doesn't seem to be an isolated issue as both my wife and I are experiencing this.

For what it's worth, we downloaded the UI and it's optional modules independently then updated them via Curse once they were installed. Perhaps something caused a conflict.

**Comment by failcoder** [comment]
If you are going to use Curse to keep it updated then delete all SVUI addon folders and download new copies from Curse. Mixing the sources has been known to cause issues.

**Comment by failcoder** [comment]
Let me know if this is still happening. I have one other profile issue that is open and need to make sure they are all squashed.

**Comment by OrbitStorm** [comment]
Sorry for the delayed response, been a busy weekend.

I can confirm this is still an issue. My wife and I deleted all SVUI folders, our Cache / WTF folders as well, and installed a fresh copy of SV via Curse. Not only are we still forced to redo the settings for every character, we're also unable to copy profile settings from our initial setup. Worst of all, the settings don't save period. We have to redo the settings on each and every log-in.

Given how tedious this is with the difficulty in scaling for bigger resolutions (this UI is clearly best suited and tailored for 1920x1080 and nothing more), it pains me to say this isn't worth the trouble keeping it installed. I've spent more time finagling with this UI than I have actually playing this past week.

I'll check back often and will be happy to give this UI another go once this particular bug is ironed out and assuming you're able to tweak the design a bit to support bigger resolutions. I don't mean any of this as a slight against your work, it's a phenomenal UI, truly. Best of luck!

**Comment by failcoder** [comment]
These are the specifics I needed, thank you. I will be testing this today and will update this ticket soon.

**Comment by OrbitStorm** [comment]
Can you provide an update on whether this has been addressed? Tried this on ONE character and it worked as of yesterday yet my wife tried and had no such luck.

**Comment by failcoder** [comment]
I have another question. Do any of your (or your wife's) toons have Cyrillic letters in their names? Such as "Ӕ", "Ф", "Ё" or any other non-standard English alpha-numeric characters...

**Comment by OrbitStorm** [comment]
Nope. We avoid names like that. :)

**Comment by failcoder** [comment]
I can now confirm that the lack of server distinction (as you pointed out) is the most probably cause to this. Since there is a new ticket for that issue, I am closing this one.
