### ISSUE TITLE
No longer one bag

### ISSUE THREAD

**Issue by Toomuchpc** [failcoder/Supervillain_UI#126]
I loaded the UI. Everything was beautiful and worked great for about the first 30 minutes.  Then I went into options and checked just one thing - auto release on PVP.  The UI reloaded and now I no longer have the pretty single bag for my own inventory or for my bank.  everything is separate and horrible - like the bliz default.  I restarted the game, changed to another toon, unchecked the PVP auto release - nothing is giving me back that beautiful combined bag and combined bank. How do I get it back?  Running the install again didn't bring it back.

**Comment by penguinsane** [comment]
Double check your addons (on the character select screen) and make sure the Bag module is enabled.

**Comment by Toomuchpc** [comment]
Hi thanks.  Not sure which is the bag module.  I did check that Inventory module was selected, but this was after I had uninstalled and reinstalled SVUI - which worked fine to correct the problem.  Sorry I didn't wait for your answer, I was too anxious to get it back to looking so nice!  Thanks anyway.
