### ISSUE TITLE
Debuff Highlight and "you Can Remove" doesn't work

### ISSUE THREAD

**Issue by Gthosty** [failcoder/Supervillain_UI#127]
When Im leveling my Mistweaver Monk throught dungeons i noticed that my Party UnitFrames never change color while player has a debuff which i can dispel (it works on a target and focus frame tho). Also when i tick "You Can remove" option in a Praty UnitFrames (debuff tab) UI shows me debuffs which I can't dispel anyways.

I love SVUI in every inch and will really love to use it while im raiding but with these 2 problems Im force to use other RaidFrames addons.

**Comment by failcoder** [comment]
This functionality was revised in a recent update. Check again and let me know if the issue persists.

**Comment by Gthosty** [comment]
It has been working perfectly since the update. Thanks a lot! SVUI rocks
man!

2015-05-22 17:11 GMT+02:00 Steven Jackson <notifications@github.com>:

**Comment by failcoder** [comment]
You are very welcome
