### ISSUE TITLE
[Bug] [1.2.5] Creating new chat tab overrides an old one

### ISSUE THREAD

**Issue by penguinsane** [failcoder/Supervillain_UI#132]
On a character that doesn't have any custom chat tabs, trying to create a new one, it overrides the Combat Log. Recreate Combat Log, it overrides the new chat tab.

**Comment by penguinsane** [comment]
Fixed for the most part, but logging in has a bunch of blank channels. Removing them works fine and it works normally after that.

http://puu.sh/hW7Po/a8190d6ab7.jpg

**Comment by failcoder** [comment]
The collection of blanks is simply a result of some of the saved variables created by using this test version prior to the last commit. A normal user would not get those.

**Comment by penguinsane** [comment]
alright, thanks.

I tried to move my chat tab over and it looks like it should have placed there, but instead left a blank area where it SHOULD be, but never moved: http://puu.sh/hXav7/e9453bfcee.jpg

**Comment by penguinsane** [comment]
Actually, closing this since it's resolved and posting this on #129.
