### ISSUE TITLE
MiniMap Display Issue

### ISSUE THREAD

**Issue by CorvusE** [failcoder/Supervillain_UI#88]
My minimap does not change appearance when I set it to square or rectangle. I'm using the up-to-date Curse download with a screen resolution of 1366x768 on OSX.

**Comment by failcoder** [comment]
Do you have the option "RotateMinimap" enabled? If so then that's why, only the round shape is allowed when this is active.

**Comment by CorvusE** [comment]
A-ha! I probably do. I'll check when we're out of maintenance this afternoon.

**Comment by CorvusE** [comment]
That did the trick, thanks!
