### ISSUE TITLE
[Bug] Versatility often doesn't display who cast it

### ISSUE THREAD

**Issue by failcoder** [failcoder/Supervillain_UI#95]
_From @penguinsane on February 8, 2015 19:52_

Should look like this: http://puu.sh/fEsOD/37ede190ac.jpg

Usually looks like this: http://puu.sh/fEsSv/37a6c31667.jpg

_Copied from original issue: failcoder/SVUI-Kit#22_

**Comment by failcoder** [comment]
fixed

**Comment by failcoder** [comment]
Fixed again, I screwed up this change and it was causing UnitClass to fail :(

**Comment by failcoder** [comment]
Confirmed?

**Comment by failcoder** [comment]
_From @penguinsane on February 12, 2015 21:41_

Sorry! Yes, looks like it's fixed, but it displays the name of the pet instead of the hunter if they're the ones providing Versatility.

Also, Trueshot Aura (Attack Power)  doesn't say that it is cast by me on my hunter, but I was not in a group at the time so that may be why.

**Comment by penguinsane** [comment]
This can probably be closed since it looks like this has been fixed.
