### ISSUE TITLE
Slider problems

### ISSUE THREAD

**Issue by failcoder** [failcoder/Supervillain_UI#99]
_From @hotluck on April 1, 2015 15:5_

I was showing my daughter the setups for your addon on one of her characters. She tends to grab onto me while she's watching which makes it very hard from me to get the sliders in the correct place (such as dock widths, etc.), so I thought I'll just click on the number underneath and manually change the number. Doesn't work. No matter what you enter, the slider will still stay at the original number. The number will only change and stay if you move the slider. I tried various ones on various screens and they were did the same.

_Copied from original issue: failcoder/SVUI-Kit#93_

**Comment by failcoder** [comment]
Do you recall which option slider this was?

**Comment by hotluck** [comment]
It was various ones. Dock width for one...there were various ones I was changing. I think most were in Unitframes like the offsets, widths and heights, that type of thing. I'd done quite a few before I realised it hadn't actually changed them.

**Comment by failcoder** [comment]
Are you hitting the enter key after making changes in these boxes?
